name: 'Publish Suggested Track'
on:
  schedule:
    - cron: '30 16 * * 1'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  publish_track:
    name: "Publish suggested track"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.head_ref }}
      - name: 'Setup Java 11'
        uses: 'actions/setup-java@v3'
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: "Download ignored tracks"
        run: 'curl https://raw.githubusercontent.com/$GITHUB_REPOSITORY/ignored-tracks/ignored.txt --output /tmp/ignored.txt'
      - name: 'Build the jar'
        run: './gradlew shadowJar'
      - name: 'Publish suggested track'
        env:
          LISTENBRAINZ_USERNAME: '${{ secrets.LISTENBRAINZ_USERNAME }}'
          TWITTER_CONSUMER_KEY: '${{ secrets.TWITTER_CONSUMER_KEY }}'
          TWITTER_CONSUMER_SECRET: '${{ secrets.TWITTER_CONSUMER_SECRET }}'
          TWITTER_ACCESS_TOKEN: '${{ secrets.TWITTER_ACCESS_TOKEN }}'
          TWITTER_ACCESS_TOKEN_SECRET: '${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}'
          MICROPUB_ACCESS_TOKEN: '${{ secrets.MICROPUB_ACCESS_TOKEN }}'
          MICROPUB_ENDPOINT: '${{ secrets.MICROPUB_ENDPOINT }}'
          IGNORED_TRACKS_FILE: '/tmp/ignored.txt'
        run: 'java -jar build/libs/wardell_listens.jar'
      - name: 'Get suggested track URL'
        id: 'track-url'
        run: 'echo "::set-output name=IGNORED_TRACK::$(tail -1 /tmp/ignored.txt)"'
      - name: 'Checkout ignored tracks branch'
        uses: 'actions/checkout@v3'
        with:
          ref: 'ignored-tracks'
      - name: 'Copy ignored tracks from temp file'
        run: 'cp /tmp/ignored.txt ignored.txt'
      - name: "Add & commit new ignored track"
        uses: 'stefanzweifel/git-auto-commit-action@v4'
        with:
          commit_message: "${{ steps.track-url.outputs.IGNORED_TRACK }}"
