name: 'Tests'
'on':
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  publish_track:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.head_ref }}
      - name: 'Setup Java 11'
        uses: 'actions/setup-java@v3'
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: 'Run the tests'
        run: './gradlew test'
